### ISSUE TITLE
Fix Ron's lower back.

### ISSUE THREAD

**Issue by ronkerensky** [ronkerensky/Test#19]
My back has been hurting- it's not supposed to work that way and needs to be resolved.

**Comment by ronkerensky** [comment]
Try using Ben-gay, if you're not too homophobic...

**Comment by ronkerensky** [comment]
Use "Freeze Gel" to try to heal my back and my bias.

**Comment by ronkerensky** [comment]
Back is feeling better, bias is still there.  Closing this issue.

**Comment by BrandonJoyce356** [comment]
You have broke-back mountain syndrome.
